version: '3'
services:
  db:
    image: postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: crypto_db
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-email-password
